{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "11160f95",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading networks from \"https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metfaces.pkl\"...\n",
      "Generating image for seed 85 (0/4) ...\n",
      "Setting up PyTorch plugin \"bias_act_plugin\"... /zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py:366: UserWarning: \n",
      "\n",
      "                               !! WARNING !!\n",
      "\n",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "Your compiler (c++ 4.8.5) may be ABI-incompatible with PyTorch!\n",
      "Please use a compiler that is ABI-compatible with GCC 5.0 and above.\n",
      "See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.\n",
      "\n",
      "See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6\n",
      "for instructions on how to install GCC 5 or higher.\n",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "\n",
      "                              !! WARNING !!\n",
      "\n",
      "  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))\n",
      "Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py\", line 48, in _init\n",
      "    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1509, in _jit_compile\n",
      "    _write_ninja_file_and_build_library(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1601, in _write_ninja_file_and_build_library\n",
      "    extra_ldflags = _prepare_ldflags(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1699, in _prepare_ldflags\n",
      "    extra_ldflags.append(f'-L{_join_cuda_home(\"lib64\")}')\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 2223, in _join_cuda_home\n",
      "    raise EnvironmentError('CUDA_HOME environment variable is not set. '\n",
      "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... /zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py:366: UserWarning: \n",
      "\n",
      "                               !! WARNING !!\n",
      "\n",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "Your compiler (c++ 4.8.5) may be ABI-incompatible with PyTorch!\n",
      "Please use a compiler that is ABI-compatible with GCC 5.0 and above.\n",
      "See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.\n",
      "\n",
      "See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6\n",
      "for instructions on how to install GCC 5 or higher.\n",
      "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "\n",
      "                              !! WARNING !!\n",
      "\n",
      "  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))\n",
      "Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1509, in _jit_compile\n",
      "    _write_ninja_file_and_build_library(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1601, in _write_ninja_file_and_build_library\n",
      "    extra_ldflags = _prepare_ldflags(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1699, in _prepare_ldflags\n",
      "    extra_ldflags.append(f'-L{_join_cuda_home(\"lib64\")}')\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 2223, in _join_cuda_home\n",
      "    raise EnvironmentError('CUDA_HOME environment variable is not set. '\n",
      "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating image for seed 265 (1/4) ...\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating image for seed 297 (2/4) ...\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\n",
      "    return _jit_compile(\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\n",
      "    module = importlib.util.module_from_spec(spec)\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating image for seed 849 (3/4) ...\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n",
      "Setting up PyTorch plugin \"upfirdn2d_plugin\"... Failed!\r\n",
      "/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py\", line 32, in _init\r\n",
      "    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/DLCV_GRP_23/Projects/Project3/stylegan2-ada-pytorch/torch_utils/custom_ops.py\", line 110, in get_plugin\r\n",
      "    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1284, in load\r\n",
      "    return _jit_compile(\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1535, in _jit_compile\r\n",
      "    return _import_module_from_library(name, build_directory, is_python_module)\r\n",
      "  File \"/zhome/3a/d/136926/DLCV/lib/python3.9/site-packages/torch/utils/cpp_extension.py\", line 1929, in _import_module_from_library\r\n",
      "    module = importlib.util.module_from_spec(spec)\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1173, in create_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n",
      "ImportError: /zhome/3a/d/136926/.cache/torch_extensions/py39_cu117/upfirdn2d_plugin/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory\r\n",
      "\r\n",
      "  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\\n\\n' + traceback.format_exc())\r\n"
     ]
    }
   ],
   "source": [
    "    !python stylegan2-ada-pytorch/generate.py --outdir=out --trunc=1 --seeds=85,265,297,849 \\\n",
    "    --network=https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metfaces.pkl"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
